[H-03]ReferralFeePoolV0.sol#claimRewardAsMochi()Array out of bound exception
Submitted by WatchPug, also found by pauliax
ReferralFeePoolV0.sol#L28L42
functionclaimRewardAsMochi()external{IUSDMusdm=engine.usdm();address[]memorypath=newaddress[](2);path[0] =address(usdm);path[1] =uniswapRouter.WETH();path[2] =address(engine.mochi());usdm.approve(address(uniswapRouter),reward[msg.sender]);// we are going to ingore the slippages hereuniswapRouter.swapExactTokensForTokens(reward[msg.sender],1,path,address(this),type(uint256).max);
InReferralFeePoolV0.sol#claimRewardAsMochi(),pathis defined as an array of length 2 while it should be length 3.
As a result, at L33, an out-of-bound exception will be thrown and revert the transaction.
Impact
claimRewardAsMochi()will not work as expected so that all the referral fees cannot be claimed but stuck in the contract.
ryuheimat (Mochi) confirmed